// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB
{
    public partial class Menu
    {
        public Menu()
        {
            InversePIDNavigation = new HashSet<Menu>();
            MenuTranslation = new HashSet<MenuTranslation>();
        }

        public string ID { get; set; }
        public string PID { get; set; }
        public string Code { get; set; }
        public long Seq { get; set; }
        public string Icon { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public long IsEnabled { get; set; }

        public virtual Menu PIDNavigation { get; set; }
        public virtual ICollection<Menu> InversePIDNavigation { get; set; }
        public virtual ICollection<MenuTranslation> MenuTranslation { get; set; }
    }
}